name: Release Compiled PDF
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex

      - uses: actions/upload-artifact@v3
        with:
          name: cv.pdf
          path: cv.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: cv.pdf
          name: latest
          tag_name: latest
